language: python
python: 
  - "3.6"
sudo: required
services:
  - docker
install: 
  - pip install -r requirements.txt
script:
  - python cloudflair.py myvulnerable.site

env:
  global:
  # Censys API ID and secret
  - secure: wM1EdpvsWKRIfWiuQT7XTTK00blbxKk7Ty6Pm5AY6r18aegnoWjxcDXhPOk3Yeqawd+r0IpAdqWDIGvUZEeMv2qzvGXMoXlhE2lkY7U6m1MXUFzxBj5aUo+ZdWDfDRLs20ZHGH3MGlZrwkTNRqjd0MpdLdqrBArMvfl/ABOmFFDsE6tQMv/TW6AaYC+a+e0orAmJY1VK9MYI8ibYezMZVNmOS+9swp4ZSIMU6Ocku0DAUYJx/szq/caHdy95ZLyaaE6CGdzXSeR0dH/uPpyig8jyL/NWmFeNpLEOH40dKS6UqL3E8QQkOVp3njgMTz9vRG1Py/9Op33vyYlfL4p48b4oFHvYA2YfOzEvgJhwDFrQUqgbqno+cPMu1R87HXRgvsYnBXucUzDKUOmIYZ7ym+hRTcDEPeyk4MOnSIlQE0n288by8iJGxyScIGl2b0FWiUMbtgozT8UC4F9GZnclh6VjW+CV2fXS/mz2Lsf2NVdGvjR4e8Jr/dwzSLbfHnqH6PhCv1YqSRNNGN0k9RBjcdjVmVh1qUfFvc6IpIbZJ7lly5C2UkFAVl4tNJQ80JerZB6hVLjz7vWKCaQjThfAgn1oFZXRqdeBTwhy8r7PshtUWz47Wp5G7RpP1gsVq63Va2G4LYKe9POGUIJoco3atCVQhehfIb2aCjg34vdxmPo=
  - secure: MTZK5/ADVf4cagvYMQU6zVaV6+8mhO/1yYRrLdxNOYixzu8ycQsARdA6nluRVFp9Ygs3icDRze/YPGqas6tlO+H2Foj+ei7eksabKX3QfZP0XtN/RUhZMZsqhV1jAuJv0bKh8i7L3pmZgiLjcDzYymeVvKfLyCdk3dREa46QQZllqzPN3xv7+A4yKqH7GeKcLD0HdC0a3aNBz25yREqDX7EhlyjWrc6XdbPsL7uHsBsgUUuxzc0xdrGcbKzcDRZxulqJ+Wf/gNaqAcr7FftMBFrRbDzPrMdh+7GuZqnqZPGVPpLsV2u72ifzeodAULVbETJjFL8F7KUsZwY7rA8zLVM6UjGfmX8i+Sm6AuQMtADodJddzMGq5J10Olwr7jM5YDimsy/NHRMKGyYxB1OZpNfI9b+5rz1dZHD+7HqgdDhIeZbzyohnGA02duktx/kgPUiNgYjzqdkOsnfRz9lGB9E/XTaDOe1bF3uiUIu8C8xWMEGjn95Ii/qasi0ToddA20kTVCAq1KhthGIT0s7XKHmvhMaHENARyhPrLTdYCaO9sfAkHK3v8gwVYb2ScCj59J9w3+JwQV2lu9HqKsz9UZcxdN+ChhmdxEb1sZYLQZdFVPM9kjr1gN5aOLTv4fcjKKZjDkpQw5weCBTT1VqEXuUx9+er16g701Vwfka49vE=
notifications:
  email: false